### PR TITLE
fix poetry.dependencies issue

### PR DESCRIPTION
**Pull request by wtracyliu**
pr to solve #9 

according the documentation of poetry [https://python-poetry.org/docs/dependency-specification/](url) ,  ^0.16.5 means >=0.16.5 <0.17.0 , so I think it's better to change ^0.16.5 to >=0.16.5

### CODE REVIEW

**Comment by s-agawane** [comment]
@wtracyliu Is this the reason I am not able to upgrade to sentry 0.17 ?

**Comment by wtracyliu** [comment]
@s-agawane   I think so, actually after pip install my forked version ,I've upgraded sentry to 0.19.1.  I've never used poetry before, so I looked up in the documentation, I think that's the problem.

**Comment by gilmrjc** [comment]
Yes, this fixes the problem because `^0.16.5` locks to versions in the `0.16.x` releases. @danielwelch just a friendly ping for this 🙏

**Review by c-goosen — APPROVED** [review]

**Comment by c-goosen** [comment]
Sorry for the delay on this @wtracyliu.

Merging in fix. Will do a build to pypi as well.

**Pull request merged**
